#!/bin/sh
#
# Shell script to test the Toolchain Docker image.
#
# Copyright 2016-2020, Frederico Martins
#   Author: Frederico Martins <http://github.com/fscm>
#
# SPDX-License-Identifier: MIT
#
# This program is free software. You can use it and/or modify it under the
# terms of the MIT License.
#

# Variables
BISON_TEST_FILE="bison.y"
GCC_TEST_FILE="gcc.c"
GXX_TEST_FILE="gxx.cc"
GLIBC_TEST_FILE="glibc.c"
MAKE_TEST_FILE="Makefile"

__LIB_DIR__="$(dirname $(readlink -f -n $(gcc --print-file-name=libc.so)))"


# Functions
create_gcc_test_files() {
  cat << EOF > /tmp/${GCC_TEST_FILE}
#include <stdio.h>
int main() {
  puts("Hello, world!");
  return 0;
}
EOF

  cat << EOF > /tmp/${GXX_TEST_FILE}
#include <iostream>
int main() {
  std::cout << "Hello, world!" << std::endl;
  return 0;
}
EOF
}

create_glibc_test_files() {
  cat << EOF > /tmp/${GLIBC_TEST_FILE}
#define _GNU_SOURCE
#include <assert.h>
#include <gnu/libc-version.h>
#include <stdatomic.h>
#include <stdio.h>
#include <threads.h>

atomic_int acnt;
int cnt;

int f(void* thr_data) {
  for(int n = 0; n < 1000; ++n) {
    ++cnt;
    ++acnt;
  }
  return 0;
}

int main(int argc, char **argv) {
  printf("gnu_get_libc_version() = %s\n", gnu_get_libc_version());
  thrd_t thr[10];
  for(int n = 0; n < 10; ++n)
    thrd_create(&thr[n], f, NULL);
  for(int n = 0; n < 10; ++n)
    thrd_join(thr[n], NULL);
  printf("The atomic counter is %u\n", acnt);
  printf("The non-atomic counter is %u\n", cnt);
}
EOF
}

create_make_test_files() {
  cat << EOF > /tmp/${MAKE_TEST_FILE}
default:
$(printf '\t')@echo 'Hello world!'
EOF
}

create_bison_test_files() {
  cat << EOF > /tmp/${BISON_TEST_FILE}
%{
#include <iostream>
using namespace std;
extern void yyerror (char *s);
extern int yylex ();
%}
%start prog
%%
prog:  /* empty */
    |  prog expr '\\n' { cout << "pass"; exit(0); }
    ;
expr:  '(' ')'
    |  '(' expr ')'
    |  expr expr
    ;
%%
char c;
void yyerror (char *s) { cout << "fail"; exit(0); }
int yylex () { cin.get(c); return c; }
int main() { yyparse(); }
EOF
}

echo '=== Docker Build Test ==='

# Create temporary dir (if needed)
if ! [ -d /tmp ]; then
  mkdir -m 1777 /tmp
fi

printf '[TEST] Creating the test files... '
create_gcc_test_files
create_glibc_test_files
create_make_test_files
create_bison_test_files
echo 'DONE'

printf '[TEST] Check if Binutils were installed... '
if ld --version > /dev/null 2>&1; then
  echo 'OK'
else
  echo 'Failed'
  exit 1
fi

printf '[TEST] Check if GCC is installed... '
if gcc --version > /dev/null 2>&1; then
  echo 'OK'
else
  echo 'Failed'
  exit 2
fi

printf '[TEST] Check if GLibC is installed... '
if (${__LIB_DIR__}/ld-*.so 2>&1 | grep -q Usage && ${__LIB_DIR__}/libc-*.so --version && locale --version) > /dev/null 2>&1; then
  echo 'OK'
else
  echo 'Failed'
  exit 3
fi

printf '[TEST] Check if M4 is installed... '
if m4 --version > /dev/null 2>&1; then
  echo 'OK'
else
  echo 'Failed'
  exit 4
fi

printf '[TEST] Check if Gettext is installed... '
if gettext --version > /dev/null 2>&1; then
  echo 'OK'
else
  echo 'Failed'
  exit 5
fi

printf '[TEST] Check if Make is installed... '
if make --version > /dev/null 2>&1; then
  echo 'OK'
else
  echo 'Failed'
  exit 6
fi

printf '[TEST] Check if Patch is installed... '
if patch --version > /dev/null 2>&1; then
  echo 'OK'
else
  echo 'Failed'
  exit 7
fi

printf '[TEST] Check if Libtool is installed... '
if libtool --version > /dev/null 2>&1; then
  echo 'OK'
else
  echo 'Failed'
  exit 8
fi

printf '[TEST] Check if Autoconf is installed... '
if autoconf --version > /dev/null 2>&1; then
  echo 'OK'
else
  echo 'Failed'
  exit 9
fi

#printf '[TEST] Check if Automake is installed... '
#if automake --version > /dev/null 2>&1; then
#  echo 'OK'
#else
#  echo 'Failed'
#  exit 10
#fi

printf '[TEST] Check if Bison is installed... '
if bison --version > /dev/null 2>&1; then
  echo 'OK'
else
  echo 'Failed'
  exit 11
fi

printf '[TEST] Check if GCC can compile... '
if (gcc -o /tmp/gcc_test /tmp/${GCC_TEST_FILE} && /tmp/gcc_test) > /dev/null 2>&1; then
  echo 'OK'
else
  echo 'Failed'
  exit 12
fi

printf '[TEST] Check if G++ can compile... '
if (g++ -o /tmp/gxx_test /tmp/${GCC_TEST_FILE} && /tmp/gxx_test) > /dev/null 2>&1; then
  echo 'OK'
else
  echo 'Failed'
  exit 13
fi

printf '[TEST] Check if GLibC can be used... '
if (gcc -pthread -o /tmp/glibc_test /tmp/${GLIBC_TEST_FILE} && /tmp/glibc_test) > /dev/null 2>&1; then
  echo 'OK'
else
  echo 'Failed'
  exit 14
fi

printf '[TEST] Check if M4 can be used... '
if (printf 'define(TEST, fscm)\nTEST\n' | m4 | grep -q fscm) > /dev/null 2>&1; then
  echo 'OK'
else
  echo 'Failed'
  exit 15
fi

printf '[TEST] Check if Gettext can be used... '
if (gettext test) > /dev/null 2>&1; then
  echo 'OK'
else
  echo 'Failed'
  exit 16
fi

printf '[TEST] Check if Make can be used... '
if (make -C /tmp) > /dev/null 2>&1; then
  echo 'OK'
else
  echo 'Failed'
  exit 17
fi

printf '[TEST] Check if Libtool can be used... '
if (libtool --quiet --mode=compile --tag=CC cc -c /tmp/${GCC_TEST_FILE} -o /tmp/libtool_test.o && libtool --quiet --mode=link --tag=CC cc /tmp/libtool_test.o -o /tmp/libtool_test && libtool execute /tmp/libtool_test) > /dev/null 2>&1; then
  echo 'OK'
else
  echo 'Failed'
  exit 18
fi

printf '[TEST] Check if Bison can be used... '
if (bison --output=/tmp/bison_test.c /tmp/${BISON_TEST_FILE} && g++ -o /tmp/bison_test /tmp/bison_test.c && echo '((()(())))()' | /tmp/bison_test | grep -q 'pass' && echo '())' | /tmp/bison_test | grep -q 'fail') > /dev/null 2>&1; then
  echo 'OK'
else
  echo 'Failed'
  exit 19
fi

printf '[TEST] Check if Busybox is installed... '
if busybox > /dev/null 2>&1; then
  echo 'OK'
else
  echo 'Failed'
  exit 20
fi

exit 0
